version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.prod
    image: tg_web_prod
    container_name: tg_web_prod
    command: /start-django
    restart: on-failure
    stdin_open: true
    tty: true
    expose:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`localhost`)"
    volumes:
      - .:/app
    env_file:
      - ./.env/.prod.env
    depends_on:
      - db
      - redis

  tg_bot:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.prod
    image: tg_bot_prod
    container_name: tg_bot_prod
    command: /start-bot
    restart: always
    volumes:
      - .:/app
    env_file:
      - ./.env/.prod.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.3
    container_name: tg_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "push_feedback_wb"
      POSTGRES_PASSWORD: "push_feedback_wb"
      POSTGRES_DB: "push_feedback_wb_prod"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U push_feedback_wb -d push_feedback_wb_prod"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  pgadmin:
    container_name: tg_pgadmin
    image: dpage/pgadmin4:6.20
    environment:
      PGADMIN_DEFAULT_EMAIL: "push_feedback_wb@tg.com"
      PGADMIN_DEFAULT_PASSWORD: "push_feedback_wb"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - '8050:80'
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: tg_redis
    volumes:
      - redis-data:/data

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.prod
    image: tg_celeryworker
    container_name: tg_celeryworker
    command: /start-worker
    restart: on-failure
    volumes:
      - .:/app
    env_file:
      - ./.env/.prod.env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.prod
    image: tg_celerybeat
    container_name: tg_celerybeat
    command: /start-beat
    restart: on-failure
    volumes:
      - .:/app
    env_file:
      - ./.env/.prod.env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.prod
    image: tg_flower
    container_name: tg_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env/.prod.env
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

  traefik:
    image: traefik:latest
    container_name: tg_traefik
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - "$PWD/compose/traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  redis-data:
  postgres_data:
